/** Pre-loaded showcase document — first-visit users see every feature themed. */
export const SAMPLE_MARKDOWN = `# Quarterly Growth Report

*Generated by an LLM — styled by markdown.style.*

Paste your own markdown to replace this sample. Everything renders live: tables, code, math, diagrams.

## Highlights

| Region | Revenue | Growth |
|--------|---------|--------|
| EMEA   | $4.2M   | +14%   |
| APAC   | $3.1M   | +22%   |
| AMER   | $6.8M   | +9%    |

- [x] Consolidate Q3 numbers
- [x] Review regional forecasts
- [ ] Board deck sign-off

## Model

Growth follows $g = r \\cdot (1 - s)$ where $r$ is raw rate and $s$ is churn share:

$$
g_{\\text{net}} = \\sum_{i=1}^{n} r_i (1 - s_i)
$$

## Pipeline

\`\`\`mermaid
graph LR
A[Leads] --> B[Qualified]
B --> C[Proposal]
C --> D[Closed]
\`\`\`

## Implementation note

\`\`\`ts
export function netGrowth(rates: number[], churn: number[]): number {
  return rates.reduce((sum, r, i) => sum + r * (1 - (churn[i] ?? 0)), 0)
}
\`\`\`

> Numbers exclude the acquisition closed after the quarter cutoff.[^1]

[^1]: See the finance memo for reconciliation details.
`

/** Short excerpt for theme-picker thumbnails — no mermaid/math so thumbs render instantly. */
export const THUMB_MARKDOWN = `# The Quick Report

A short paragraph showing body text, a [link](https://example.com), and \`inline code\`.

| Item | Value |
|------|-------|
| One  | 42    |
| Two  | 7     |

\`\`\`ts
const answer = 42
\`\`\`
`
